### PR TITLE
Drop Python 2 support

### PR DESCRIPTION
**Pull request by icemac**
I created a guide line at https://github.com/zopefoundation/meta/wiki/Remove-Python-2-support and used this package as example.

### CODE REVIEW

**Comment by dataflake** [comment]
I'm wondering in general what the best "schedule" is for this complete switch. Do you want to switch dependencies before publishing some Zope 5 alpha or beta? Or do you want Zope to go first and dependencies can switch at their own pace? There's no urgency for any of these options that I can see.

**Comment by dataflake** [comment]
P.S.: Coming back to your comment yesterday: When we start doing this we definitely will need the equivalent of that Zope 2.13 version ranges file.

**Comment by icemac** [comment]
@dataflake We could release a Zope 5 alpha at any time and work through the dependencies later. Removing Python 2 support from the dependencies should not block the Zope 5 release. I'll look into a solution for Zope 4 to have maximum versions.

**Comment by jugmac00** [comment]
I guess this ship has sailed, but I am a bit skeptic whether dropping Py2 support already now will bring some pain for those who are still in transition to Py3.

**Comment by dataflake** [comment]
There is no pain because they can either pin their version manually or packages like Zope do it for them.

**Comment by mauritsvanrees** [comment]
In Plone you would first migrate to Plone 5.2 on Python 2.7, then migrate your ZODB to Python 3 (with `zodbupgrade`), and then use Plone 5.2 on Python 3.
I suppose for Zope projects it would be similar: you would first migrate to Zope 4 on Python 2.7, then migrate your ZODB to Python 3, and then use Zope 4 (or later 5) on Python 3.

**Comment by dataflake** [comment]
Yes, that's the procedure. The role of Zope 4 is to be that stepping stone for the Python 2 to 3 conversion. Once that is done (and once Zope 5 is out) we want to encourage people to switch to Zope 5 because that code base will have all those workarounds for compatibility removed and will be easier to maintain in the long run.

**Comment by dataflake** [comment]
@icemac Don't you want to create a maintenance branch from the point in time before this merge, something like a 3.x?

**Comment by jugmac00** [comment]
When the dependencies get pinned, you no longer just update from Python 2 to 3, but at the same time you have to update those pinned dependencies, which probably developed further.
(update - right, you don't have to do it at once)

Once there was a `promise`, that updating from Zope 4 to Zope 5 will be "effortless", as only Py3 gets dropped.

This would be only true if all bugfixes of the dependencies get backported to the Py2/Py3 versions.. which is quite some effort for the maintainers, and which I do not see this will happen.

I think that the maintenance burden for keeping two branches and backporting is much higher than keeping the py2/py3 comp a bit longer - but that is only me, and of course you do the work, so be it.

Anyway - it's done. I am running Zope 4 on Py2 in prod, and Zope 4 on Py3 in dev. I won't be affected much, but we'll see how this works out.

**Comment by dataflake** [comment]
You vastly overestimate the bug fixing that happens in those dependencies. Zope 4 to Zope 5 aims to be effortless, that is correct.

Are you implying that your buildouts do not use the version requirements files that come with the Zope version you use as basis, such as using them in a buildout configuration `extends` statement? Because changing that to the Zope 5 version should get you most of the way there on the Zope 5 upgrade once you're finishd with the Python 3 migration under Zope 4.

**Comment by icemac** [comment]
@dataflake We can create a `3.x` branch once we need it to back port fixes from master in future.

**Comment by dataflake** [comment]
I have created it yesterday because right now it's quick and easy to find the right branch point.

I suggest for any package where we make the "clean Python 3 break" we do create such a branch as a matter of habit before merging in the changes. Even if we never end up using it.

**Comment by icemac** [comment]
@dataflake Good idea I am going to add this to https://github.com/zopefoundation/meta/wiki/Remove-Python-2-support.

**Comment by dataflake** [comment]
Oh that's where that wiki was... I didn't have the link and couldn't find it in the usual places (on the Zope project or on the zopefoundation organization)...

**Pull request merged**
