### PR TITLE
Add preliminary support for Python 3.12rc1

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by dataflake** [comment]
The errors under Python 3.12 are actually a `zope.testrunner` issue: https://github.com/zopefoundation/zope.testrunner/issues/149

**Comment by dataflake** [comment]
The errors disappear with https://github.com/zopefoundation/zope.testrunner/pull/150 applied.

**Comment by dataflake** [comment]
This PR will go green when zope.testrunner 6.1 is on PyPI, I'm just waiting for the required privileges.

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing and working on this PR. 😃

**Pull request merged**
